pipeline:
  build:
    image: node:12-alpine
    environment:
      - REACT_APP_HASURA_API_URL=https://api-graphql.staging.bonde.org/v1/graphql
      - REACT_APP_LOGIN_URL=https://accounts.staging.bonde.org/login
      - REACT_APP_DOMAIN_CROSS_STORAGE=https://cross-storage.staging.bonde.org
    commands:
      - export REACT_APP_GOOGLE_CLIENT_KEY=$STAG_GOOGLE_CLIENT
      - yarn global add pnpm
      - pnpm i
      - pnpm m run build
    secrets: [ stag_google_client, stag_zendesk_token, stag_zendesk_user ]
    when:
      event: [push]

  production-build:
    image: node:12-alpine
    environment:
      - REACT_APP_HASURA_API_URL=https://api-graphql.bonde.org/v1/graphql
      - REACT_APP_LOGIN_URL=https://admin-canary.bonde.org/auth/login
      - REACT_APP_DOMAIN_CROSS_STORAGE=https://cross-storage.bonde.org
    commands:
      - export REACT_APP_GOOGLE_CLIENT_KEY=$STAG_GOOGLE_CLIENT
      - yarn global add pnpm
      - pnpm i
      - pnpm m run build
    secrets: [ stag_google_client, stag_zendesk_token, stag_zendesk_user ]
    when:
      event: [tag]

  publish-stag-redes:
    image: plugins/docker
    repo: nossas/bonde-redes
    group: publishing
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]
      event: push

  publish-prod-redes:
    image: plugins/docker
    repo: nossas/bonde-redes
    group: publishing
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG##v}
      - latest
    when:
      status: success
      event: tag

  deploy-stag-solidarity-client:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webservers/client-redes
    group: deploying
    docker_image: nossas/bonde-redes:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]
      event: push

  deploy-prod-solidarity-client:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webservers/client-redes
    docker_image: "nossas/bonde-redes:${DRONE_TAG##v}"
    timeout: 360
    group: deploying
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  deploy-stag-listener-redes:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: listeners/redes
    group: deploying
    docker_image: nossas/bonde-redes:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]
      event: push

  deploy-prod-listener-redes:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: listeners/redes
    docker_image: "nossas/bonde-redes:${DRONE_TAG##v}"
    timeout: 360
    group: deploying
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  deploy-stag-listener-redes-geolocation:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: listeners/redes-geolocation
    group: deploying
    docker_image: nossas/bonde-redes:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]
      event: push

  deploy-prod-listener-redes-geolocation:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: listeners/redes-geolocation
    docker_image: "nossas/bonde-redes:${DRONE_TAG##v}"
    timeout: 360
    group: deploying
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag