pipeline:
  webhooks-registry-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhooks-registry
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhooks-registry/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  webhooks-registry-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/registry
    group: deploying
    docker_image: nossas/bonde-webhooks-registry:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  webhooks-registry-production-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/registry
    docker_image: "nossas/bonde-webhooks-registry:${DRONE_TAG##v}"
    timeout: 360
    group: deploy
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  webhooks-zendesk-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhooks-zendesk
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhooks-zendesk/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  webhooks-zendesk-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/zendesk
    group: deploying
    docker_image: nossas/bonde-webhooks-zendesk:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  webhooks-zendesk-production-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/zendesk
    docker_image: "nossas/bonde-webhooks-zendesk:${DRONE_TAG##v}"
    timeout: 360
    group: deploy
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  cli-zendesk-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-cli-zendesk
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/cli-zendesk/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  webhooks-solidarity-count-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhooks-solidarity-count
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhooks-solidarity-count/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  webhooks-solidarity-match-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhooks-solidarity-match
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhooks-solidarity-match/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  webhook-mail-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhook-mail
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhook-mail/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  webhook-mail-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/mail
    group: deploying
    docker_image: nossas/bonde-webhook-mail:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]

  webhook-mail-production-publish:
    image: plugins/docker
    repo: nossas/bonde-webhook-mail
    group: publish
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhook-mail/Dockerfile
    tags:
      - ${DRONE_TAG##v}
      - latest
    when:
      status: success
      event: tag

  webhook-mail-production-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/mail
    docker_image: "nossas/bonde-webhook-mail:${DRONE_TAG##v}"
    timeout: 360
    group: deploy
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag

  webhook-activists-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhook-activists
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhook-activists/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  webhook-activists-staging-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/activists
    group: deploying
    docker_image: nossas/bonde-webhook-activists:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]


  webhook-activists-production-publish:
    image: plugins/docker
    repo: nossas/bonde-webhook-activists
    group: publish
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhook-activists/Dockerfile
    tags:
      - ${DRONE_TAG##v}
      - latest
    when:
      status: success
      event: tag

  webhook-activists-production-deploy:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webhooks/activists
    docker_image: "nossas/bonde-webhook-activists:${DRONE_TAG##v}"
    timeout: 360
    group: deploy
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag