pipeline:
  registry-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhooks-registry
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhooks-registry/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  zendesk-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhooks-zendesk
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhooks-zendesk/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  convert-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhooks-convert
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhooks-convert/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  # registry-staging-deploy:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/registry
  #   docker_image: nossas/bonde-webhooks-registry:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
