pipeline:
  build:
    image: node:10-alpine
    environment:
      - COMMUNITY_ID=40
      - REACT_APP_ZENDESK_ORGANIZATIONS={"lawyer":360269610652,"individual":360273031591,"therapist":360282119532}
      - ZENDESK_API_URL=https://mapadoacolhimento.zendesk.com/api/v2/
      - REACT_APP_LOGIN_URL=https://admin-canary.staging.bonde.org/auth/login
      - REACT_APP_DOMAIN_CROSS_STORAGE=https://cross-storage.staging.bonde.org
    commands:
      - export REACT_APP_GOOGLE_CLIENT_KEY=$STAG_GOOGLE_CLIENT
      - export ZENDESK_API_TOKEN=$STGA_ZENDESK_API_TOKEN
      - export ZENDESK_API_USER=$STGA_ZENDESK_API_USER
      - yarn global add pnpm
      - pnpm i
      - pnpm m run build
    secrets: [stag_google_client, stag_zendesk_token, stag_zendesk_user]
    when:
      event: [push]

  production-build:
    image: node:10-alpine
    environment:
      - COMMUNITY_ID=40
      - REACT_APP_ZENDESK_ORGANIZATIONS={"lawyer":360269610652,"individual":360273031591,"therapist":360282119532}
      - ZENDESK_API_URL=https://mapadoacolhimento.zendesk.com/api/v2/
      - REACT_APP_LOGIN_URL=https://admin-canary.bonde.org/auth/login
      - REACT_APP_DOMAIN_CROSS_STORAGE=https://cross-storage.bonde.org
    commands:
      - export REACT_APP_GOOGLE_CLIENT_KEY=$STAG_GOOGLE_CLIENT
      - export ZENDESK_API_TOKEN=$STGA_ZENDESK_API_TOKEN
      - export ZENDESK_API_USER=$STGA_ZENDESK_API_USER
      - yarn global add pnpm
      - pnpm i
      - pnpm m run build
    secrets: [stag_google_client, stag_zendesk_token, stag_zendesk_user]
    when:
      event: [tag]

  # publish-stag-webhooks-registry:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-registry
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-registry/Dockerfile
  #   tags:
  #     - ${DRONE_BRANCH/\//-}
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
  #     event: push

  # publish-prod-webhooks-registry:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-registry
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-registry/Dockerfile
  #   tags:
  #     - ${DRONE_TAG##v}
  #     - latest
  #   when:
  #     status: success
  #     event: tag

  # publish-stag-webhooks-zendesk:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-zendesk
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-zendesk/Dockerfile
  #   tags:
  #     - ${DRONE_BRANCH/\//-}
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
  #     event: push

  # publish-prod-webhooks-zendesk:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-zendesk
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-zendesk/Dockerfile
  #   tags:
  #     - ${DRONE_TAG##v}
  #     - latest
  #   when:
  #     status: success
  #     event: tag

  # publish-stag-webhooks-solidarity-count:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-solidarity-count
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-solidarity-count/Dockerfile
  #   tags:
  #     - ${DRONE_BRANCH/\//-}
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
  #     event: push

  # publish-prod-webhooks-solidarity-count:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-solidarity-count
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-solidarity-count/Dockerfile
  #   tags:
  #     - ${DRONE_TAG##v}
  #     - latest
  #   when:
  #     status: success
  #     event: tag

  # # Solidarity match dont works

  # publish-stag-webhooks-solidarity-match:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-solidarity-match
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-solidarity-match/Dockerfile
  #   tags:
  #     - ${DRONE_BRANCH/\//-}
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
  #     event: push

  # publish-prod-webhooks-solidarity-match:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-solidarity-match
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhooks-solidarity-match/Dockerfile
  #   tags:
  #     - ${DRONE_TAG##v}
  #     - latest
  #   when:
  #     status: success
  #     event: tag

  # publish-stag-webhooks-mail:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-mail
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhook-mail/Dockerfile
  #   tags:
  #     - ${DRONE_BRANCH/\//-}
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
  #     event: push

  # publish-prod-webhooks-mail:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-mail
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhook-mail/Dockerfile
  #   tags:
  #     - ${DRONE_TAG##v}
  #     - latest
  #   when:
  #     status: success
  #     event: tag

  # publish-stag-webhooks-activists:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-activists
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhook-activists/Dockerfile
  #   tags:
  #     - ${DRONE_BRANCH/\//-}
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
  #     event: push

  # publish-prod-webhooks-activists:
  #   image: plugins/docker
  #   repo: nossas/bonde-webhooks-activists
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/webhook-activists/Dockerfile
  #   tags:
  #     - ${DRONE_TAG##v}
  #     - latest
  #   when:
  #     status: success
  #     event: tag

  # publish-stag-cli-mautic:
  #   image: plugins/docker
  #   repo: nossas/bonde-cli-mautic
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/cli-mautic/Dockerfile
  #   tags:
  #     - ${DRONE_BRANCH/\//-}
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
  #     event: push

  # publish-prod-cli-mautic:
  #   image: plugins/docker
  #   repo: nossas/bonde-cli-mautic
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/cli-mautic/Dockerfile
  #   tags:
  #     - ${DRONE_TAG##v}
  #     - latest
  #   when:
  #     status: success
  #     event: tag

  # publish-stag-cli-zendesk:
  #   image: plugins/docker
  #   repo: nossas/bonde-cli-zendesk
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/cli-zendesk/Dockerfile
  #   tags:
  #     - ${DRONE_BRANCH/\//-}
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, support/*, develop]
  #     event: push

  # publish-prod-cli-zendesk:
  #   image: plugins/docker
  #   repo: nossas/bonde-cli-zendesk
  #   group: publishing
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: packages/cli-zendesk/Dockerfile
  #   tags:
  #     - ${DRONE_TAG##v}
  #     - latest
  #   when:
  #     status: success
  #     event: tag

  publish-stag-solidarity-client:
    image: plugins/docker
    repo: nossas/bonde-solidarity-client
    group: publishing
    secrets: [docker_username, docker_password]
    dockerfile: packages/solidarity-client/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]
      event: push

  publish-prod-solidarity-client:
    image: plugins/docker
    repo: nossas/bonde-solidarity-client
    group: publishing
    secrets: [docker_username, docker_password]
    dockerfile: packages/solidarity-client/Dockerfile
    tags:
      - ${DRONE_TAG##v}
      - latest
    when:
      status: success
      event: tag

  # deploy-stag-webhooks-registry:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/registry
  #   group: deploying
  #   docker_image: nossas/bonde-webhooks-registry:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push

  # deploy-prod-webhooks-registry:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/registry
  #   docker_image: "nossas/bonde-webhooks-registry:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag

  # deploy-stag-cli-zendesk-user:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/cli-zendesk-user
  #   group: deploying
  #   docker_image: nossas/bonde-cli-zendesk:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push

  # deploy-stag-cli-zendesk-ticket:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/cli-zendesk-ticket
  #   group: deploying
  #   docker_image: nossas/bonde-cli-zendesk:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push

  # deploy-prod-cli-zendesk-user:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/cli-zendesk-user
  #   docker_image: "nossas/bonde-cli-zendesk:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag

  # deploy-prod-cli-zendesk-ticket:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/cli-zendesk-ticket
  #   docker_image: "nossas/bonde-cli-zendesk:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag

  # deploy-stag-cli-mautic:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/cli-mautic
  #   group: deploying
  #   docker_image: nossas/bonde-cli-mautic:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push

  # deploy-prod-cli-mautic:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/cli-mautic
  #   docker_image: "nossas/bonde-cli-mautic:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag

  # deploy-stag-webhooks-zendesk:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/zendesk
  #   group: deploying
  #   docker_image: nossas/bonde-webhooks-zendesk:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push

  # deploy-prod-webhooks-zendesk:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/zendesk
  #   docker_image: "nossas/bonde-webhooks-zendesk:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag

  # deploy-stag-webhooks-solidarity-count:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/solidarity-count
  #   group: deploying
  #   docker_image: nossas/bonde-webhooks-solidarity-count:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push

  # deploy-prod-webhooks-solidarity-count:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/solidarity-count
  #   docker_image: "nossas/bonde-webhooks-solidarity-count:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag

  # deploy-stag-webhooks-solidarity-match:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/solidarity-match
  #   group: deploying
  #   docker_image: nossas/bonde-webhooks-solidarity-match:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push

  # deploy-prod-webhooks-solidarity-match:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/solidarity-match
  #   docker_image: "nossas/bonde-webhooks-solidarity-match:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag

  # deploy-stag-webhooks-mail:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/mail
  #   group: deploying
  #   docker_image: nossas/bonde-webhooks-mail:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push

  # deploy-prod-webhooks-mail:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/mail
  #   docker_image: "nossas/bonde-webhooks-mail:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag

  # deploy-stag-webhooks-activists:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/activists
  #   group: deploying
  #   docker_image: nossas/bonde-webhooks-activists:${DRONE_BRANCH/\//-}
  #   timeout: 360
  #   confirm: true
  #   secrets: [ rancher_access_key, rancher_secret_key ]
  #   when:
  #     status: success
  #     branch: [hotfix/*, release/*, feature/*, develop]
  #     event: push

  # deploy-prod-webhooks-activists:
  #   image: peloton/drone-rancher
  #   url: http://cluster.bonde.org
  #   service: webhooks/activists
  #   docker_image: "nossas/bonde-webhooks-activists:${DRONE_TAG##v}"
  #   timeout: 360
  #   group: deploying
  #   confirm: true
  #   secrets:
  #     - source: rancher_access_key_prod
  #       target: rancher_access_key
  #     - source: rancher_secret_key_prod
  #       target: rancher_secret_key
  #   when:
  #     status: success
  #     event: tag

  deploy-stag-solidarity-client:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webservers/match-voluntarias
    group: deploying
    docker_image: nossas/bonde-solidarity-client:${DRONE_BRANCH/\//-}
    timeout: 360
    confirm: true
    secrets: [rancher_access_key, rancher_secret_key]
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, develop]
      event: push

  deploy-prod-solidarity-client:
    image: peloton/drone-rancher
    url: http://cluster.bonde.org
    service: webservers/match-voluntarias
    docker_image: "nossas/bonde-solidarity-client:${DRONE_TAG##v}"
    timeout: 360
    group: deploying
    confirm: true
    secrets:
      - source: rancher_access_key_prod
        target: rancher_access_key
      - source: rancher_secret_key_prod
        target: rancher_secret_key
    when:
      status: success
      event: tag
