pipeline:
  registry-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhooks-registry
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhooks-registry/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  zendesk-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhooks-zendesk
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhooks-zendesk/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  auth-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-webhooks-auth
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/webhooks-auth/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]

  jsonb-convert-staging-publish:
    image: plugins/docker
    repo: nossas/bonde-cli-jsonb-convert
    group: publishing
    secrets: [ docker_username, docker_password ]
    dockerfile: packages/cli-jsonb-convert/Dockerfile
    tags:
      - ${DRONE_BRANCH/\//-}
    when:
      status: success
      branch: [hotfix/*, release/*, feature/*, support/*, develop]