packages:
  - "."
  - "packages/webhooks-zendesk"
  - "packages/webhooks-registry"
  - "packages/cli-zendesk"
  - "packages/webhooks-solidarity-count"
  - "packages/client-solidarity"
  - "packages/listener-solidarity"
  # - "packages/cli-mautic"
  # - "packages/webhooks-solidarity-match"
  # - "packages/webhook-mail"
