packages:
  - '.'
  - 'packages/cli-mautic'
  - 'packages/cli-zendesk'
  - 'packages/webhooks-auth'
  - 'packages/webhooks-registry'
  - 'packages/webhooks-solidarity-count'
  - 'packages/webhooks-solidarity-match'
  - 'packages/webhooks-zendesk'
  - 'packages/webhook-mail'
  - 'packages/webhook-activists'
  - 'packages/solidarity-client'
